
environment:
  CODECAKEBUILDER_SECRET_KEY:
    secure: 8VAzdXgUQaJyFoU3WLf2iPFV/8zPDm9qV4TfOpx8/rg=
  SqlServer/MasterConnectionString: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
  API_KEY_TO_PUSH_NPM_PACKAGES:
    secure: ABYojwv0/UimKKf8vhsD2UlHeqm25UMSwav+rFU3d0R3DTLRq+gXbMftWieRXya1hnJbkzgLf6evzxGEtSQ9WUhCyphEO2i0pNEfHEdYceSWTbWBiDu0v2/39Rw3hQS0kdb3bNMknI/BhLv1vNg+WQ==
services: mssql2017
install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1
version: build{build}
image: Visual Studio 2019
clone_folder: C:\CKli-World\CK-Core-Projects\CK-SqlServer-Dapper
branches:
  only:
    - master
    - develop
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
artifacts:
  - path: '**\*.log'
    name: Log file
  - path: '**\*.trx'
    name: Visual studio test results file
  - path: '**\Tests\**\TestResult*.xml'
    name: NUnit tests result files
  - path: '**Tests\**\Logs\**\*'
    name: Log files
